CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    category VARCHAR(255) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    transaction_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT transactions_type_check CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT transactions_amount_check CHECK (amount > 0)
);

CREATE INDEX idx_transactions_date ON transactions (transaction_date DESC);
CREATE INDEX idx_transactions_type_date ON transactions (type, transaction_date DESC);
CREATE INDEX idx_transactions_category ON transactions (category);
