CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    CONSTRAINT categories_type_check CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT categories_name_type_unique UNIQUE (name, type)
);

INSERT INTO categories (name, type) VALUES
    ('ЗП', 'INCOME'),
    ('Аренда', 'INCOME'),
    ('Прочие источники', 'INCOME'),
    ('Еда домой', 'EXPENSE'),
    ('Еда улица', 'EXPENSE'),
    ('Еда доставки', 'EXPENSE'),
    ('Одежда', 'EXPENSE'),
    ('Долги', 'EXPENSE'),
    ('Машина', 'EXPENSE'),
    ('КУ', 'EXPENSE'),
    ('КУ (Пушкин)', 'EXPENSE'),
    ('Досуг', 'EXPENSE'),
    ('Транспорт', 'EXPENSE'),
    ('Такси/самики', 'EXPENSE'),
    ('Для дома', 'EXPENSE'),
    ('Подписки', 'EXPENSE'),
    ('Подарки', 'EXPENSE'),
    ('Интернет и связь', 'EXPENSE'),
    ('Маркетплейсы', 'EXPENSE');
