CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE transactions
    ADD COLUMN vehicle_id BIGINT REFERENCES vehicles(id);

INSERT INTO vehicles (name) VALUES ('Основной автомобиль');

UPDATE transactions
SET vehicle_id = (SELECT id FROM vehicles WHERE name = 'Основной автомобиль')
WHERE category = 'Машина';

CREATE INDEX idx_transactions_vehicle_date
    ON transactions (vehicle_id, transaction_date DESC);
