spring:
  datasource:
    url: jdbc:h2:file:./data/finance-tracker;MODE=PostgreSQL;DATABASE_TO_UPPER=false;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:5173
